### ISSUE TITLE
no longer works in brave (possibly all chromium browsers)

### ISSUE THREAD

**Issue by paerbac** [gordalina/gmail-unsubscribe#1]
ctrl + u just opens the source code now :(

**Comment by gordalina** [comment]
Can you try to re-bind the shortcut in chrome://extensions/shortcuts ?

**Comment by paerbac** [comment]
I was able to fix it that way, thanks for making a super helpful and open source extension btw

**Comment by gordalina** [comment]
Which keyboard shortcut did you use instead? I think we should rebind the shortcut specifically for windows.

**Comment by paerbac** [comment]
I switched it to alt-u, also im not on windows, I'm using a flatpak version of brave on Arch with the Gnome 42 DE, so just know it could be working fine on windows for all I know

**Comment by gordalina** [comment]
Changed the default windows/linux shortcut to Alt+U. It will be released in v0.1.0
Thank you for reporting!
